/**
 * The agent's odds input: a RECORDED REPLAY of real captured TxLINE wire records, replayed
 * through the real `SharpDetector`.
 *
 * The artifact is generated by `backend/scripts/export_web_artifacts.py` from the on-disk
 * capture (gigabytes, outside the repo) — the browser gets a small contiguous window of it.
 * Nothing here is synthesized: every `pct` and every `ts` came off the live TxODDS API during
 * the capture window, and every move was flagged by the real detector at the real threshold.
 *
 * It is RECORDED, not live. Anything that renders this data must say so — see
 * {@link provenanceLabel}.
 */

import replayJson from "@/data/agent-replay.json";

export interface Reading {
  /** Capture timestamp, ms since epoch — the real moment the book moved. */
  ts: number;
  /** Implied probability of the outcome, in percentage points. */
  pct: number;
}

export interface DetectedMove {
  ts: number;
  bookmaker: string;
  market: string;
  outcome: string;
  old_pct: number;
  new_pct: number;
  delta_pct: number;
  direction: "up" | "down";
}

export interface ReplaySlice {
  provenance: {
    kind: "recorded-replay";
    source: string;
    note: string;
    captureFromMs: number;
    captureToMs: number;
    generatedAt: string;
  };
  fixture: {
    id: number;
    participant1: string;
    participant2: string;
    competition: string;
    competitionId: number;
    kickoffMs: number;
  };
  detector: {
    thresholdPct: number;
    readingsObserved: number;
    movesFlagged: number;
  };
  line: {
    bookmaker: string;
    market: string;
    outcome: string;
    readingsOnLine: number;
    windowStart: number;
    windowEnd: number;
  };
  series: Reading[];
  moves: DetectedMove[];
}

export const REPLAY = replayJson as ReplaySlice;

export function fixtureLabel(slice: ReplaySlice = REPLAY): string {
  return `${slice.fixture.participant1} v ${slice.fixture.participant2}`;
}

/** A human market label — the raw TxLINE line id is exported verbatim so it stays auditable. */
export function lineLabel(slice: ReplaySlice = REPLAY): string {
  const [market, params] = slice.line.market.split("|");
  const pretty = market
    .toLowerCase()
    .replace(/_/g, " ")
    .replace("overunder participant goals", "over/under goals");
  return params ? `${pretty} (${params.replace("line=", "")})` : pretty;
}

export function formatCaptureDate(ms: number): string {
  return new Date(ms).toLocaleDateString(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export function formatCaptureTime(ms: number): string {
  return new Date(ms).toISOString().slice(11, 19) + "Z";
}

/** The provenance line every view of this data must show. */
export function provenanceLabel(slice: ReplaySlice = REPLAY): string {
  return `Recorded replay · real ${slice.provenance.source} capture · ${fixtureLabel(slice)} · ${formatCaptureDate(slice.provenance.captureFromMs)}`;
}

/** The index in `series` the flagged move landed on, or -1 when it falls outside the window. */
export function moveIndex(slice: ReplaySlice = REPLAY): number {
  const move = slice.moves[0];
  if (!move) return -1;
  return slice.series.findIndex((r) => r.ts === move.ts);
}

/** The move the exported series actually shows (same book, same line), if any. */
export function movesOnThisLine(slice: ReplaySlice = REPLAY): DetectedMove[] {
  return slice.moves.filter(
    (m) => m.market === slice.line.market && m.outcome === slice.line.outcome,
  );
}
